# Description: revert the logarithm in seurat derived data
# note that due to size the data is not given in the respective folders, but needs to be generated by the Seurat pipeline if necessary
#
# author Sascha Schäuble
# date of creation: Tue May 15 12:20:06 2024
# license: MIT

library("data.table")

transform_data <- function(df) {
	df.exp <- exp( df[,-1] )
	df.exp <- df.exp - 1
	df.exp2 <- cbind(df[,1], df.exp) 
	return(df.exp2)
}

# brain
bra <- fread("../dat/snRNA/brain_SCT_matrix.tsv")
bra.exp <- transform_data(bra)
fwrite(bra.exp, file = "../dat/snRNA/brain_SCT_matrix_delog.tsv", sep = "\t")

# kidney
kid <- fread("../dat/snRNA/kidney_SCT_matrix.tsv")
kid.exp <- transform_data(kid)
fwrite(kid.exp, file = "../dat/snRNA/kidney_SCT_matrix_delog.tsv", sep = "\t")

# # liver
liv <- fread("../dat/snRNA/liver_SCT_matrix.tsv")
liv.exp <- transform_data(liv)
fwrite(liv.exp, file = "../dat/snRNA/liver_SCT_matrix_delog.tsv", sep = "\t")

# wat
wat <- fread("../dat/snRNA/wat_SCT_matrix.tsv")
wat.exp <- transform_data(wat)
fwrite(wat.exp, file = "../dat/snRNA/wat_SCT_matrix_delog.tsv", sep = "\t")
